# Generated by Django 3.1.7 on 2021-04-14 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_mensaje', models.DateTimeField()),
                ('asunto', models.CharField(max_length=50)),
                ('texto', models.TextField()),
                ('leido', models.BooleanField()),
                ('id_emisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_emisor', to='nuc.usuario')),
                ('id_receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_receptor', to='nuc.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Especialista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('fecha_nac', models.DateTimeField()),
                ('foto', models.CharField(max_length=100)),
                ('biografia', models.CharField(max_length=255)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nuc.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=100)),
                ('fecha_nac', models.DateTimeField()),
                ('foto', models.CharField(max_length=100)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nuc.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cita', models.DateTimeField()),
                ('informe', models.TextField()),
                ('realizada', models.BooleanField()),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nuc.cliente')),
                ('id_especialista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nuc.especialista')),
            ],
        ),
    ]
